### ISSUE TITLE
Add licience please

### ISSUE THREAD

**Issue by MikhailNatalenko** [matheusgomes28/base64pp#1]
Hello! Your lib looks solid. But I'm not sure if i can use it. It looks pretty match that you would like to share it, but still... 

So could you specify any known licience on this, please?

**Comment by matheusgomes28** [comment]
@MikhailNatalenko Hi! It's nice to know that people actually want to use this 😄  

I'll look up the best licenses for this project. But out of interest, how would you use this in your codebase? This may or may not affect which license I add.

**Comment by MikhailNatalenko** [comment]
@matheusgomes28 Sorry for a long answer. I'm looking for a simple solution in the commercial project i'm involved to. It's hard to explain the idea of our tool.

**Comment by matheusgomes28** [comment]
@MikhailNatalenko I've added the MIT license. Should allow for commercial use of this code as well as closed source modifications.

Let me know if that's enough. If so, I'll close this issue.

**Comment by MikhailNatalenko** [comment]
@matheusgomes28 Thank you for a quick responce. It's totally ok!
