### ISSUE TITLE
[RFC] Package for OpenEmbedded/Yocto Linux

### ISSUE THREAD

**Issue by ceggers-arri** [matheusgomes28/base64pp#112]
I have created a build recipe for OpenEmbedded (which is the base of the Yocto distribution).

Some questions:
- Do you like base64pp to be included into Linux distributions?
- Alternative: Do you like to postpone this?
- Do you want to create a release version for this? [optional]
- Do you like to use Unix (LF) line endings instead of Windows (CRLF)? [optional]

```
SUMMARY = "A Modern & Safe C++ Encoder"
AUTHOR = "Matheus Gomes"
HOMEPAGE = "https://github.com/matheusgomes28/base64pp"
BUGTRACKER = "https://github.com/matheusgomes28/base64pp/issues"
SECTION = "libs"
LICENSE = "MIT"
LIC_FILES_CHKSUM = "file://LICENSE;md5=2b86b91216ea23de57837d22445846f5"

PV .= "+git${SRCPV}"

SRC_URI = " \
    git://git.arri.de/lighting/r-d/software/3rd-party/base64pp.git;protocol=ssh;user=git;branch=main \
"

SRCREV = "5c057af9f2f183e8ac98d5880986a19c369865f6"

S = "${WORKDIR}/git"

inherit cmake dos2unix

PACKAGECONFIG ??= "shared"
PACKAGECONFIG[shared] = "-DBUILD_SHARED_LIBS=ON,-DBUILD_SHARED_LIBS=OFF,,"

# main package is always empty, debug package is empty if building as a static library
ALLOW_EMPTY:${PN} = "1"
ALLOW_EMPTY:${PN}-dbg = "1"

PACKAGES =+ "libbase64pp "
# base64pp has no SOVERSION yet
FILES:libbase64pp += "${libdir}/libbase64pp.so"
RDEPENDS:${PN}-dev = "libbase64pp (= ${EXTENDPKGV})"
```

**Comment by matheusgomes28** [comment]
Hey @ceggers-arri , good to see you again! Sorry for delayed reply (dayjob 😢 )

I've used Yocto before when I was an embedded software engineer, so I'm happy to support that usecase! I never really used OpenEmbedded recipes before, I think I remember using bitbake for different packages. Hence I can't technically help much here, but I'm happy to do some research and try.

Ideally, if it requires many config files & infra code, I'd like to keep it separate from this repo. As an example, I've recently added Conan recipes which now need to live elsewhere as it's not really part of the build.

Regarding the changes needed for this support:

> Do you like base64pp to be included into Linux distributions?
Absolutely, but hopefully this doesn't mean lowering the standard of C++ for the sake of compilation in older compilers.

> Alternative: Do you like to postpone this?
Let me think once I get an idea of how much work this will need.

> Do you want to create a release version for this? [optional]
Yes, I can create releases whenever needed. In fact, with the overload changes we made recently, the repo probably needs a new release.

> Do you like to use Unix (LF) line endings instead of Windows (CRLF)? [optional]
Good point. I think I started development on this in Windows over a year ago or so. Happy to `dos2unix` all the files, should be very quick.

**Comment by matheusgomes28** [comment]
@ceggers-arri From what I gather in this conversation, do we agree on the following?

- Create the OpenEmbedded recipe in a remote repo. (I can help you with maintenance once I read more about them, given there's demand).
- Support the "target" mode as to avoid major changes in API & implementation.
- [DONE] Removed all the carriage returns from text files.

Let me know if I missed anything 😄

**Comment by matheusgomes28** [comment]
I'll do a new release tomorrow to include all the recent changes.

**Comment by ceggers-arri** [comment]
> @ceggers-arri From what I gather in this conversation, do we agree on the following?
> 
>     * Create the OpenEmbedded recipe in a remote repo. (I can help you with maintenance once I read more about them, given there's demand).
> 
>     * Support the "target" mode as to avoid major changes in API & implementation.
> 
>     * [DONE in [Running "dos2unix" on all text files #113](https://github.com/matheusgomes28/base64pp/pull/113) ] Removed all the carriage returns from text files.
> 

Yes, correct. The current main branch is fine for me. As soon as you like I can submit the recipe to OpenEmbedded.

Of course there is no guarantee that they will accept the recipe...

**Comment by matheusgomes28** [comment]
> Of course there is no guarantee that they will accept the recipe...

Let's hope they do! At least something we both contributed to may be used by more people. Besides, it's a good exercise to test this library in different embedded environments.

**Comment by matheusgomes28** [comment]
I'm gonna close this as it seems this conversation is done. Feel free to open more issue / feature requests if needed!
