### ISSUE TITLE
Is this a typo?

### ISSUE THREAD

**Issue by liuyangc3** [matheusgomes28/base64pp#2]
see this [line](https://github.com/matheusgomes28/base64pp/blob/main/base64pp/base64pp.cpp#L53), should it be below?
```patch
-   if ((c >= 'a') && ('z'))
+   if ((c >= 'a') && (c <= 'z'))
```

**Comment by liuyangc3** [comment]
> Hi @liuyangc3 , I believe it is a typo!
> 
> Would you like to push a PR or should I push it myself? I would be very grateful if you want to fix it and increase your Github contributions :)

Sure, I've submitted the PR, see https://github.com/matheusgomes28/base64pp/pull/3

**Comment by matheusgomes28** [comment]
Thanks for fixing with #3 . I'll close this issue now :)
