### ISSUE TITLE
Install the library files and headers with CMake

### ISSUE THREAD

**Issue by matheusgomes28** [matheusgomes28/base64pp#77]
Need to install the library with CMake, so users can call `cmake install`

Suggested structure:

- `${INSTALL_DIR}/lib` holds the library files (`.a`, `.lib`). 📖 
- `${INSTALL_DIR}/include` holds the public header files. 🎧 

Relevant video: [Deep CMake for library writers](https://www.youtube.com/watch?v=m0DwB4OvDXk).

**Comment by matheusgomes28** [comment]
> like to work on it

@ayushmaanshrotriya sounds good! Let me know if you need help but it should just be about using the `install(...)` cmake command on the `base64pp` target defined in `base64pp/CMakeLists.txt`

**Comment by ayushmaanshrotriya** [comment]
some help is needed though

**Comment by matheusgomes28** [comment]
> some help is needed though

@ayushmaanshrotriya you're basically going to use the [Cmake "install" function](https://cmake.org/cmake/help/latest/command/install.html) on the target `base64pp` . Take a look at the link but you will need to install the lib with the `LIBRARY` option, and the header file with the `FILE` option.

**Comment by matheusgomes28** [comment]
@ayushmaanshrotriya I'm gonna pick this up as I need it for a different task. Let me know if you've done anything on this and I could wait
